/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Payment;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-06-02T20:27:40.761Z[GMT]")
@Validated
public interface PaymentsApi {

    @Operation(summary = "Make a payment", description = "", tags={ "payment" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid data in the payment JSON"),
        
        @ApiResponse(responseCode = "200", description = "successful operation") })
    @RequestMapping(value = "/payments/",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<String> makePayment(@RequestHeader("idempotency-key") String idempotencyKey, @Parameter(in = ParameterIn.DEFAULT, description = "payment object", required=true, schema=@Schema()) @Valid @RequestBody Payment body);

}

