openapi: "3.0.2"
info:
  description: "Microservice CC2"
  version: "1.0.0"
  title: "Microservice CC2"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "ddafonseca@myges.fr"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "PaymentAPI"
    description: "Payment API [CC2 microservice]"
paths:
  /payments/:
    post:
      tags:
        - "payment"
      summary: "Make a payment"
      description: ""
      operationId: "makePayment"
      requestBody:
        description: "payment object"
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        default:
          description: "successful operation"
        "400":
          description: "Invalid data in the payment JSON"

components:
  schemas:
    BuyerInfo:
      type: "object"
      properties:
        id:
          type: "string"
        username:
          type: "string"
        firstName:
          type: "string"
    CreditCardInfo:
      type: "object"
      properties:
        type:
          type: "string"
        code:
          type: "string"
        ccv:
          type: "string"
        expiry_date:
          type: "string"
          format: "date"
    PaymentOrders:
      type: "object"
      properties:
        payment_orders_id:
          type: "string"
    Payment:
      type: "object"
      properties:
        buyer_info:
          $ref: "#/components/schemas/BuyerInfo"
        checkout_id:
          type: "string"
          description: "A globally unique ID for this checkout"
        credit_card_info:
          $ref: "#/components/schemas/CreditCardInfo"
        amount:
          type: "string"
          description: "The transaction amount of the order"
        currency:
          type: "string"
          description: "The currency for the order"
          example: "EUR"
          